//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//
//     As alterações feitas neste arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguradosPOC
{


    public partial class Cadastro
    {

        /// <summary>
        /// Controle btnTestarConexao.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnTestarConexao;

        /// <summary>
        /// Controle lblResultadoConexao.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblResultadoConexao;
    }
}
